-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 26/01/2018 19:44:20
-- Server version: 5.5.5-10.1.19-MariaDB
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE gestortareas;

--
-- Definition for table tareas
--
DROP TABLE IF EXISTS tareas;
CREATE TABLE tareas (
  id_tarea INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  descripcion VARCHAR(255) DEFAULT NULL,
  categoria VARCHAR(255) NOT NULL,
  prioridad VARCHAR(255) NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  propietario VARCHAR(255) NOT NULL,
  PRIMARY KEY (id_tarea),
  INDEX FK_tareas_usuarios_username (propietario)
)
ENGINE = INNODB
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

--
-- Definition for table usuarios
--
DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL DEFAULT ' ',
  email VARCHAR(50) NOT NULL,
  hash VARCHAR(255) NOT NULL DEFAULT ' ',
  `check` TINYINT(1) DEFAULT 0,
  nombre VARCHAR(255) DEFAULT NULL,
  apellidos VARCHAR(255) DEFAULT NULL,
  admin TINYINT(4) DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE INDEX email (email),
  UNIQUE INDEX usuario (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_spanish_ci;

-- 
-- Dumping data for table tareas
--
INSERT INTO tareas VALUES
(6, 't2', 'trabajo en equipo', '2', 'alta', '1901-12-05', '1901-12-08', 'anuska'),
(9, 't3', 'inventario', '1', 'media', '2018-01-19', '2018-02-03', 'anuska'),
(10, 't3', 'firmas', '8', 'alta', '2018-01-31', '2018-01-31', 'silvia'),
(11, 't3', 'firmas', '8', 'alta', '2018-01-31', '2018-01-31', 'silvia');

-- 
-- Dumping data for table usuarios
--
INSERT INTO usuarios VALUES
(1, 'anuska', '$2y$13$l9m9pa/kNVh9DCGyWRi.3uQcwIqCt.uWiP5xUABWnbLTvZ8nG0bXa', 'sanmamedana@gmail.com', 'VNkPMpCmSPnntzOju61sMx9cC4_QMKW6', 1, 'anuska', 'anuska', 1),
(2, 'silvia', '$2y$13$BiMwMX.v5mTWCKSTn2cCWOjpNjeAGZZkH8bEyM6ToasRnhuPbjpvK', 'silvia.gomeza@gmail.com', 'X0GjIYbWv9L55TfBBNbMZN3jSct2ms-a', 1, 'silvia', 'silvia', 0);

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;